# Site settings
title: Jorge Morales Lorenzo - Web Developer
description: "PJ de la Web"
baseurl: "" # for test: remove string '/space-jekyll-templa' to ''
url: "http://cv.jmlorenzo.es" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.githu.io'
# User settings
username: Jorge Morales Lorenzo
user_title: PJ de la Web
email: info@jmlorenzo.es
twitter_username: jmlorenzo50
github_username:  jmlorenzo50
gplus_username:  na
disqus_username: loremipsum
profile_picture: https://pbs.twimg.com/profile_images/1157552740/avatar_400x400.png

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: none
  comments: none
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: Inicio
    url: /
  - title: Experiencia Laboral
    url: /proyectos
  - title: Formación
    url: /formacion
  
# projects in header index
projects:
  - name: StawDial
    url: https://github.com/jmlorenzo50/StawDial

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
